name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install npm dependencies
        run: |
          # 1. 强制切换国内淘宝镜像源（下载速度快100倍）
          npm config set registry https://registry.npmmirror.com
          # 2. 忽略老旧的依赖冲突
          npm install --legacy-peer-deps
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install npm dependencies
        run: |
          # 同样，在编译阶段也全局换源
          npm config set registry https://registry.npmmirror.com
          npm install --legacy-peer-deps
      - name: Build Android Release
        run: |
          cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
